Adds oss repository
qub-it/qub-fenixedu-project pull request #2
Opened 2023-12-11 14:01 UTC by joaofreitas-qubit

2023-12-11 15:23 UTC, joaojtmarques-qubit approved these changes

2023-12-12 12:04 UTC, pabrantes requested changes
The only change I'm requesting is checking the formatting because it seems off to me.
Besides that we just have to remember to publish this pom as soon as it gets merged as well so it goes into the OSS repository.

2023-12-12 12:04 UTC, pabrantes commented on pom.xml
> +				<id>ulisboa-repo</id>
@joaofreitas-qubit there seems to be some formatting issues here. Can you fix that?

2023-12-12 12:04 UTC, pabrantes commented on pom.xml
> +			<url>https://repository-oss.omnis.cloud/nexus/repository/releases/</url>
@joaofreitas-qubit we should publish a new version of this project so it get's into the OSS repository.

2023-12-13 13:26 UTC, merged